DAY 6

Class

In [ ]:
class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model
    def demo(self):
        print(f"This {self.brand} is ready for demo")

car1=Car("BMW","XS")
print(car1.brand)
print(car1.model)
car1.demo()


BMW
XS
This BMW is ready for demo


In [7]:
class User:
    def __init__(self,salary):
        self.salary=salary
    
    def addSalary(self,amount):
        self.salary+=amount
    def showSalary(self):
        print(f"Salary is: {self.salary}")

    def deductSalary(self,amount):
        self.salary-=amount

user1=User(5000)
user1.showSalary()
user1.addSalary(2000)
user1.showSalary()
user1.deductSalary(1000)
user1.showSalary()

#Directly change by calling class
user1=User(50000)
user1.showSalary()

Salary is: 5000
Salary is: 7000
Salary is: 6000
Salary is: 50000


In [ ]:
class animal:
    def sound(self):
        print("Animal makes sound")

class dog(animal):
    def sound(self):
        print("Dog barks")

c=dog()
c.sound()

Dog barks


Numpy

In [36]:
import numpy as np

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
# print(a)
print(a[0:2,1:3])
mask=a>50
print(a[mask])

# print(a.shape)
# print(a.ndim)
# print(a.size)
# print(a.dtype)

# # print(a.reshape(6))
# # print(a.flatten())
# # print(a.ravel())
# print(a.shape[0])
# print(a.shape[1])

[[20 30]
 [50 60]]
[60 70 80 90]


In [49]:
x=np.array([[1,2,3],[4,5,6]])

print(np.sum(x))
print(np.min(x))
print(np.max(x))
print(np.mean(x))
print(np.std(x))
print(np.var(x))

print(np.sum(x,axis=1))

21
1
6
3.5
1.707825127659933
2.9166666666666665
[ 6 15]


numpy se scientific calc bnana hay

In [ ]:
#broadcasting
a=np.array([[1,2,3],[4,5,6]])
b=np.array([1,0,1])
print(a+b)

[[2 2 4]
 [5 5 7]]


In [52]:
from numpy import linalg as lg

m=np.array([[1,2],[3,4]])
print(lg.det(m))
print(lg.inv(m))
print(m.T)

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 3]
 [2 4]]


In [66]:
rand_arr=np.random.rand(3,3)
rand_ints=np.random.randint(0,255,(3,3))
normal_dist=np.random.normal(0,1,5)
print(rand_ints)
normalized=rand_ints/255.0
print(normalized)
# print(rand_arr)

[[ 96 117 232]
 [191 189 204]
 [254 247 245]]
[[0.37647059 0.45882353 0.90980392]
 [0.74901961 0.74117647 0.8       ]
 [0.99607843 0.96862745 0.96078431]]


HW- utf encoding,regex,regex.io,how to create dataframe --> total rows-50,col-10,csv me laana hay then original data not chatgpt created